// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeycthbpdluinmlslfxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleWN0aGJwZGx1aW5tbHNsZnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDI4NzgsImV4cCI6MjA3MTcxODg3OH0.jSqceUPG9pN2HziL0mcA-3CqDGpnloBC48K_Kk39GfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});